# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

    - name: install dependencies
      run: npm install

    - name: run markdownlint
      run: make markdownlint

  yamllint:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
      with:
        python-version: '3.x'

    - name: install yamllint
      run: make install-yamllint

    - name: run yamllint
      run: yamllint . -f github

  misspell:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

    - name: run misspell
      run: make misspell

  markdownlinkcheck:
    name: markdownlinkcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31  # v1.0.17
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/.mlc_config.json'

  sanity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

    - name: run sanitycheck.py
      run: python3 ./internal/tools/sanitycheck.py

  checklicense:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
    - name: install tools
      run: make install-tools
    - name: run checklicense
      run: make checklicense
